# Generated by Django 3.0.5 on 2021-06-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HamroPasal', '0002_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('Khalti', 'Khalti')], default='Cash on Delivery', max_length=20),
        ),
    ]
