# Generated by Django 3.0.5 on 2021-07-01 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HamroPasal', '0003_auto_20210628_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('Khalti', 'Khalti'), ('Esewa', 'Esewa')], default='Cash on Delivery', max_length=20),
        ),
    ]
